
USE AdventureWorksDW2022

--TOTAL DE VENDAS EM TODOS OS ANOS

SELECT
	FORMAT(SUM(SalesAmount), 'C0') AS 'VENDAS_TOTAL'
FROM FactInternetSales


--TOTAL DE CUSTO EM TODOS OS ANOS

SELECT
	FORMAT(SUM(TotalProductCost), 'C0') AS 'CUSTO_TOTAL'
FROM FactInternetSales


--QTDE TOTAL DE VENDAS REALIZADAS

SELECT
	COUNT(OrderQuantity) AS 'QTDE_TOTAL_VENDAS'
FROM FactInternetSales


--VENDAS POR CADA PAIS EM TODOS OS ANOS

USE AdventureWorksDW2022;

WITH VENDAS_POR_PAIS (ANO, VENDAS, PAIS) AS

(
SELECT
	DATEPART(YEAR ,F.ShipDate) AS 'ANO',
	SUM(F.SalesAmount) AS 'VENDAS',
	D.SalesTerritoryCountry AS 'PAIS'
FROM FactInternetSales F
INNER JOIN DimSalesTerritory D ON D.SalesTerritoryKey = F.SalesTerritoryKey
GROUP BY DATEPART(YEAR ,F.ShipDate), D.SalesTerritoryCountry
)

SELECT
	ANO,
	FORMAT(VENDAS, 'C0') AS 'VENDAS',
	PAIS
FROM VENDAS_POR_PAIS
--WHERE PAIS = 'AUSTRALIA' 'CANADA' 'FRANCE' 'GERMANY' 'UNITED KINGDOM' 'UNITED STATES'
ORDER BY ANO ASC, PAIS ASC
